refboard/refboard/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("search.urls")),
    path("thing/", include("thing.urls")),
    path("upload/", include("upload.urls")),
    path("search/", include("search.urls")),
    path("admin/", admin.site.urls),
]

refboard/search/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:ref_material_id>/', views.detail, name='detail'),
]

refboard/thing/urls.py
from django.urls import path

from . import views


app_name = "thing"
urlpatterns = [
    path("", views.index, name="index"),
    path("delete/<int:thing_id>/", views.delete_thing, name="delete_thing"),
    path("thingy/delete/<int:thingy_id>/", views.delete_thingy, name="delete_thingy"),
    path("<int:thing_id>/search/", views.detail_thing, name="detail_thing"),
    path("<int:thing_id>/", views.view_thing, name="view_thing"),
    path("thingy/<int:thingy_id>/", views.detail_thingy, name="detail_thingy"),
    path("add/", views.add_thing, name="add_thing"),
    path("<int:thing_id>/thingy/add/", views.add_thingy, name="add_thingy"),
    path(
        "append_to_thing/<int:thingy_id>", views.append_to_thing, name="append_to_thing"
    ),
]

refboard/upload/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("file-upload/", views.file_upload, name="file_upload"),
]

refboard/thing/models.py
from django.db import models

from utils.models import Thing, Thingy, RefMaterial

refboard/upload/models.py
from django.db import models

from utils.models import RefMaterial

# Create your models here.

refboard/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

refboard/utils/models.py
from django.db import models
from django.utils import timezone

MATERIAL_TYPE = ( 
    ("image", "image"), 
    ("video", "video"), 
    ("website", "website")
) 


class RefMaterial(models.Model):
    name = models.CharField("name", max_length=255)
    filename = models.CharField("filename", max_length=255)
    thumbnail = models.CharField("thumbnail", max_length=255)
    medium = models.CharField("medium", max_length=255)
    m_type = models.CharField( 
        max_length = 20, 
        choices = MATERIAL_TYPE, 
        default = 'image'
        )

    def __str__(self):
        return self.name


class Thing(models.Model):
    name = models.CharField("name", max_length=255)
    client = models.CharField("client", max_length=255)
    init_date = models.DateTimeField("init date", default=timezone.now)

    def __str__(self):
        return self.name


class Thingy(models.Model):
    name = models.CharField("name", max_length=255)
    thing = models.ForeignKey(Thing, on_delete=models.CASCADE, related_name="things")
    ref_materials = models.ManyToManyField(RefMaterial, related_name="ref_materials")

    def __str__(self):
        return self.name

refboard/thing/forms.py
from django import forms


class NewThingForm(forms.Form):
    thing_name = forms.CharField(label="New Thing", max_length=255)


class NewThingyForm(forms.Form):
    thingy_name = forms.CharField(label="New Thingy", max_length=255)

refboard/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

refboard/search/views.py
from django.shortcuts import render

from .models import RefMaterial


def index(request):
    all_refs = RefMaterial.objects.all()
    context = {'ref_materials': all_refs}

    return render(request, 'search/index.html', context)


def detail(request, ref_material_id):
    ref_material = RefMaterial.objects.get(id=ref_material_id)
    context = {'ref_material': ref_material}

    return render(request, 'search/detail.html', context)

refboard/thing/views.py
from ast import literal_eval

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Thing, Thingy, RefMaterial
from .forms import NewThingForm, NewThingyForm


def index(request):
    all_the_things = Thing.objects.all().order_by("-init_date")
    new_thing_form = NewThingForm()
    new_thingy_form = NewThingyForm()

    context = {
        "things": all_the_things,
        "new_thing_form": new_thing_form,
        "new_thingy_form": new_thingy_form,
    }

    return render(request, "thing/index.html", context)


def _helper_parse_dropped_ref(data):
    ref_objs = []
    for raw_ref_id in data:
        try:
            cleaned = int(raw_ref_id.split("_")[-1])
            ref = RefMaterial.objects.get(id=cleaned)
            ref_objs.append(ref)
        except:
            pass

    return ref_objs


def append_to_thing(request, thingy_id):
    if request.method == "POST":
        for k, v in request.POST.items():
            ref_ids = _helper_parse_dropped_ref(literal_eval(k))
            thingy = Thingy.objects.get(id=thingy_id)
            thingy.ref_materials.add(*ref_ids)

        return HttpResponseRedirect(reverse("thing:index"))

    return redirect("thing:index")


def detail_thing(request, thing_id):
    thing = Thing.objects.get(id=thing_id)
    new_thingy_form = NewThingyForm()
    all_refs = RefMaterial.objects.all()
    context = {
        "thing": thing,
        "ref_materials": all_refs,
        "new_thingy_form": new_thingy_form,
    }

    return render(request, "search/index.html", context)


def view_thing(request, thing_id):
    thing = Thing.objects.get(id=thing_id)
    thingys = Thingy.objects.filter(thing=thing.id)
    print(thingys)
    context = {
        "thing": thing,
        'thingys': thingys
        }

    return render(request, "thing/view_thing.html", context)


def detail_thingy(request, thingy_id):
    thingy = Thingy.objects.get(id=thingy_id)
    context = {"thingy": thingy}

    return render(request, "thing/detail_thingy.html", context)


def add_thing(request):
    # TODO: add user validation
    if request.method == "POST":
        form = NewThingForm(request.POST)
        if form.is_valid():
            new_thing = Thing(name=form.cleaned_data["thing_name"])
            new_thing.save()

            return HttpResponseRedirect(reverse("thing:index"))

    return redirect("thing:index")


def add_thingy(request, thing_id):
    # TODO: add user validation
    if request.method == "POST":
        form = NewThingyForm(request.POST)
        if form.is_valid():
            new_thingy = Thingy(name=form.cleaned_data["thingy_name"])
            new_thingy.thing = Thing.objects.get(id=thing_id)
            new_thingy.save()

            # return HttpResponseRedirect(reverse("thing:index"))
            return HttpResponseRedirect(f"/thing/{thing_id}/search/")

    return HttpResponseRedirect(reverse("thing:index"))


def delete_thing(request, thing_id):
    thing = Thing.objects.get(id=thing_id)
    thing.delete()

    return redirect("thing:index")


def delete_thingy(request, thingy_id):
    thingy = Thingy.objects.get(id=thingy_id)
    thingy.delete()

    return redirect("thing:index")

refboard/upload/views.py
import os

from django.shortcuts import render
from django.conf import settings

from .models import RefMaterial
from .modules import upload


def index(request):
    test_data = {"some": "data", "to": "test"}
    context = {"data_test": test_data}

    return render(request, "upload/index.html", context)


def file_upload(request):
    if request.method == "POST":
        mem_files = upload.fetch_files(request)
        for mem_file in mem_files:
            orig_name, renamed = upload.upload_to_server(mem_file)
            medium_size_name = upload.make_medium(settings.MEDIA_ROOT, renamed)
            thumb_name = upload.make_thumb(settings.MEDIA_ROOT, renamed)
            # TODO: upload files to online storage
            new_ref = RefMaterial(
                name=orig_name,
                filename=renamed,
                thumbnail=thumb_name,
                medium=medium_size_name,
            )
            new_ref.save()

    return render(request, "upload/index.html")

refboard/users/views.py
from django.shortcuts import render

# Create your views here.

refboard/utils/views.py
from django.shortcuts import render

# Create your views here.

refboard/refboard/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'refboard/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'refboard/simplebar.css' %}">
  <script src="{% static 'refboard/js/dropzone.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'search/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'thing/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/simplebar/4.0.0/simplebar.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simplebar/4.0.0/simplebar.css" />
  <script src="https://unpkg.com/feather-icons"></script>
  <title></title>



  <style>
    #dest_move {
      border: 5px solid blue;
      width: 290px;
      height: 50;
    }
  </style>
  <script>

    Dropzone.options.myAwesomeDropzone = {
      paramName: "file", // The name that will be used to transfer the file
      maxFilesize: 20, // MB
      uploadMultiple: true,
      // accept: function (file, done) {
      //   if (file.name == "test.jpg") {
      //     done("Naha, you don't.");
      //   }
      //   else { done(); }
      // }
    };

    function dragstart_handler(ev) {
      console.log("dragStart");
      // Change the source element's background color to signify drag has started
      ev.currentTarget.style.border = "dashed";
      // Add the id of the drag source element to the drag data payload so
      // it is available when the drop event is fired
      ev.dataTransfer.setData("text", ev.target.id);
      // Tell the browser both copy and move are possible
      ev.effectAllowed = "copyMove";
    }
    function dragover_handler(ev) {
      console.log("dragOver");
      // Change the target element's border to signify a drag over event
      // has occurred
      ev.preventDefault();
      ev.currentTarget.style.background = "lightblue";
      ev.currentTarget.style.border = "5px dashed";

    }
    function dragleave_handler(ev) {
      ev.currentTarget.style.background = "none";
      ev.currentTarget.style.border = "5px solid blue";
    }
    function drop_handler(ev) {
      console.log("Drop");
      ev.preventDefault();
      // Get the id of drag source element (that was added to the drag data
      // payload by the dragstart event handler)
      var id = ev.dataTransfer.getData("text");
      // Only Move the element if the source and destination ids are both "move"
      if (id.startsWith("src_mov") && ev.target.id == "dest_move") {
        var draggable = document.getElementById(id)
        draggable.style.height = "auto";
        draggable.style.width = "25%";

        ev.target.appendChild(draggable);
        ev.target.height = "auto";
        ev.target.style.border = "none";
      }
    }

    function dragend_handler(ev) {
      console.log("dragEnd");
      // Restore source's border
      ev.target.style.border = "none";
      // Resize drop zone
      var dropzone = ev.path[1];
      dropzone.style.height = "auto";
      dropzone.style.background = "none";
      dropzone.style.border = "5px solid blue";
      // Remove all of the drag data
      ev.dataTransfer.clearData();
    }

    function sendRefMatIds(thingy_id, data) {
      console.log(thingy_id);
      var xhttp = new XMLHttpRequest();
      xhttp.open("POST", "/thing/append_to_thing/" + thingy_id, true);
      xhttp.setRequestHeader("X-CSRFToken", '{{ csrf_token }}')
      xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
      xhttp.send(JSON.stringify(data));
    }

    function collectRefMatIds(thingy_id) {
      console.log(thingy_id);
      var ref_ids = []
      var parent = event.target.parentNode;
      var dropzone = parent.children[0].children;
      for (var i = 0; i < dropzone.length; i++) {
        if (dropzone[i].className === 'masonry-item') {
          ref_ids.push(dropzone[i].id);
        }
      }
      sendRefMatIds(thingy_id, ref_ids)
    }
  </script>



</head>

<body>

  <div class="site-header">
    <h1 class="site-title"><a href="/">things</a></h1>
    <h2 class="site-menu">
      <a href="/thing/">things</a>
      <a href="/search/">search</a>
      <a href="/upload/">upload</a>
    </h2>
  </div>



  <div class="site-body">
    {% block content %}{% endblock %}
  </div>

  <script>
    feather.replace()
  </script>

</body>

</html>

refboard/search/templates/search/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
SEARCH
<hr>
search bar
<hr>

{{ref_material}}
<div style="height: 80vh">
    <img style="height: 100%;" src="{% static 'search/img/temp/'|add:ref_material.filename %}">
</div>

<br>
<br>
<br>
<br>

<small>{{data_test}}</small>
{% endblock %}

refboard/search/templates/search/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="search-content">
    {% if thing %}
    <div id="left-nav">


        <div style="padding: 20px;">


            <h3 style="margin: 0px;"><a href="/thing/{{thing.id}}/search/">{{thing.name}}</a></h3>



            <span>{{thing.client}}</span>
            <p></p>
            <form action="/thing/{{thing.id}}/thingy/add/" method="post">
                {% csrf_token %}
                {{ new_thingy_form }}
                <input type="submit" value="Add">
            </form>


        </div>
        <div class="item-body">


            {% for thingy in thing.things.all %}
            <div class="thingy-content">
                <div class="thingy-content-header">
                    <h3><a href="/thing/thingy/{{thingy.id}}">{{thingy}}</a></h3>

                    <a style="font-size: 12px;padding-left:10px;" href="/thing/editthingy">edit</a>,
                    <a style="font-size: 12px;" href="/thing/thingy/delete/{{thingy.id}}">delete</a>
                </div>

                <div style="display: flex;flex-wrap: wrap;">


                    {% for ref in thingy.ref_materials.all %}
                    <a href="/search/{{ref.id}}/">
                        <img style="padding:1px; width: 50px;height: auto;border-radius: 5px"
                            src="{% static 'search/img/temp/'|add:ref.thumbnail %}">
                    </a>

                    {% endfor %}



                </div>



                <div class="drop-zone">
                    <div style="height: 50px; width: 95%;" id="dest_move" ondrop="drop_handler(event);"
                        ondragover="dragover_handler(event);" ondragleave="dragleave_handler(event);">
                        drop zone<br>
                    </div>
                    <input type="button" value="Update Reference" onclick="collectRefMatIds('{{thingy.id|safe}}');" />
                </div>


            </div>
            {% endfor %}


        </div>





    </div>
    {% endif %}
    <div id="right-nav">





        <div class="masonry">

            {% for ref in ref_materials %}
            <div class="masonry-item" draggable="true" id="src_move_{{ref.id}}" ondragstart="dragstart_handler(event);"
                ondragend="dragend_handler(event);">
                <a draggable="false" href="/search/{{ref.id}}/">
                    <img style="width: 100%; display: block;" draggable="false"
                        src="{% static 'search/img/temp/'|add:ref.medium %}">
                </a>
            </div>
            {% endfor %}


        </div>




















    </div>
</div>


<script>
    new SimpleBar(document.getElementById('left-nav'));
</script>


<small>{{data_test}}</small>


{% endblock %}

refboard/thing/templates/thing/detail_thingy.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="masonry">

        {% for ref in thingy.ref_materials.all %}
        <div class="masonry-item" style="position: relative;">
                <div class="masonry-info">
                        <i class="masonry-info-type" data-feather="image"></i>
                        <div style="display: flex;">
                                <i class="masonry-info-avatar"
                                        style="background-image: url({% static 'thing/img/user01.jpg' %});">
                                </i>
                                <i class="masonry-info-avatar"
                                        style="background-image: url({% static 'thing/img/user01.jpg' %});">
                                </i>
                        </div>
                </div>










                <a href="/search/{{ref.id}}/">
                        <img style="width: 100%; display: block;" src="{% static 'search/img/temp/'|add:ref.medium %}">
                </a>
        </div>
        {% endfor %}


</div>





{% endblock %}

refboard/thing/templates/thing/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="submenu">

    <form action="{% url 'thing:add_thing' %}" method="post">
        {% csrf_token %}
        {{ new_thing_form }}
        <input type="submit" value="Add">
    </form>

</div>


<div class="container">

    {% for thing in things %}

    <div class="item">


        <div class="item-header">

            <div class="item-header-img">
                <div class="ribbon"><strong>DUE DATE</strong></div>
            </div>
            <div class="item-header-content">
                <div class="item-header-title">
                    <h3><a href="/thing/{{thing.id}}">{{thing.name}}</a></h3>

                    <div><a href="/thing/{{thing.id}}/search/">edit</a> <a href="/thing/delete/{{thing.id}}">delete</a>
                    </div>
                </div>

                <h5>{{thing.client}}</h5>

            </div>

        </div>

        <div class="item-body">

            <form action="/thing/{{thing.id}}/thingy/add/" method="post">
                {% csrf_token %}
                {{ new_thingy_form }}
                <input type="submit" value="Add">
            </form>


            {% for thingy in thing.things.all %}
            <div class="thingy-content">
                <div class="thingy-content-header">
                    <h3><a href="/thing/thingy/{{thingy.id}}">{{thingy}}</a></h3>

                    <a style="font-size: 12px;padding-left:10px;" href="/thing/editthingy">edit</a>,
                    <a style="font-size: 12px;" href="/thing/thingy/delete/{{thingy.id}}">delete</a>
                </div>

                <div style="display: flex;flex-wrap: wrap;">


                    {% for ref in thingy.ref_materials.all %}
                    <a href="/search/{{ref.id}}/">
                        <img style="padding:1px; width: 50px;height: auto;border-radius: 5px"
                            src="{% static 'search/img/temp/'|add:ref.thumbnail %}">
                    </a>

                    {% endfor %}



                </div>
            </div>
            {% endfor %}



        </div>

    </div>





    {% endfor %}






</div>





{% endblock %}

refboard/thing/templates/thing/view_thing.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="lb-container" onclick="closeOnClick(this)">

    <img style="width: 100%; display: block;" src="{% static 'search/img/temp/01_2015_cgarchitects_large.jpg' %}">

</div>


<div class="masonry">

    {% for thingy in thingys %}

    {% for ref in thingy.ref_materials.all %}
    {% if ref.m_type == 'image' %}
    <div class="masonry-item" style="position: relative;cursor: pointer;"
        onclick="showLightbox(this, '{% static 'search/img/temp/'|add:ref.medium %}')">
        <div class="masonry-info">
            <i class="masonry-info-type" data-feather="image"></i>
            <div style="display: flex;">
                <i class="masonry-info-avatar" style="background-image: url({% static 'thing/img/user01.jpg' %});">
                </i>
                <i class="masonry-info-avatar" style="background-image: url({% static 'thing/img/user01.jpg' %});">
                </i>
            </div>
        </div>

        <img style="width: 100%; display: block;" src="{% static 'search/img/temp/'|add:ref.medium %}">

    </div>
    {% elif ref.m_type == 'video' %}
    <div class="masonry-item" style="position: relative;cursor: pointer;"
        onclick="showLightbox(this, '{% static 'search/img/temp/'|add:ref.medium %}')">
        <div class="masonry-info">
            <i class="masonry-info-type" data-feather="film"></i>
            <div style="display: flex;">
                <i class="masonry-info-avatar" style="background-image: url({% static 'thing/img/user01.jpg' %});">
                </i>
                <i class="masonry-info-avatar" style="background-image: url({% static 'thing/img/user01.jpg' %});">
                </i>
            </div>
        </div>

        <img style="width: 100%; display: block;" src="{% static 'search/img/temp/'|add:ref.medium %}">

    </div>
    {% elif ref.m_type == 'website' %}
    <div class="masonry-item" style="position: relative;cursor: pointer;"
        onclick="showLightbox(this, '{% static 'search/img/temp/'|add:ref.medium %}')">
        <div class="masonry-info">
            <i class="masonry-info-type" data-feather="image"></i>
            <div style="display: flex;">
                <i class="masonry-info-avatar" style="background-image: url({% static 'thing/img/user01.jpg' %});">
                </i>
                <i class="masonry-info-avatar" style="background-image: url({% static 'thing/img/user01.jpg' %});">
                </i>
            </div>
        </div>

        <img style="width: 100%; display: block;" src="{% static 'search/img/temp/'|add:ref.medium %}">

    </div>
    {% endif %}
    {% endfor %}

    {% endfor %}
</div>



<script>
    let showLightbox = function (el, data) {
        console.log(el)
        console.log(data)
        let lb = document.getElementById('lb-container')
        lb.style.display = 'flex';
        lb.children[0].src = data;
    }

    let closeOnClick = function (el) {
        el.style.display = 'none'
    }
</script>





{% endblock %}

refboard/upload/templates/upload/index.html
{% extends "base.html" %}
{% block content %}

UPLOAD
<hr>



<form action="/upload/file-upload/" class="dropzone" id="my-awesome-dropzone" enctype="multipart/form-data">
    {% csrf_token %}
</form>



<br>
<br>
<br>
<br>
<small>{{data_test}}</small>

{% endblock %}